version: '2'
services:
  mongodb:
    hostname: easytravel-mongodb
    container_name: mongodb
    image: "dynatrace/easytravel-mongodb"
    ports:
    - 27017
    - 28017
    restart: always

  backend:
    hostname: easytravel-backend
    container_name: backend
    image: "dynatrace/easytravel-backend"
    ports:
    - 8080
    links:
    - mongodb
    environment:
      CATALINA_OPTS: "-Dconfig.apmServerDefault=${ET_APM_SERVER_DEFAULT} -Xmx300m"
      ET_DATABASE_LOCATION: "easytravel-mongodb:27017"
    restart: always

  frontend:
    hostname: easytravel-frontend
    container_name: frontend
    image: "dynatrace/easytravel-frontend"
    ports:
    - 8080
    links:
    - backend
    - mongodb
    environment:
      CATALINA_OPTS: "-Dconfig.apmServerDefault=${ET_APM_SERVER_DEFAULT} -Xmx525m"
      ET_BACKEND_URL: "http://easytravel-backend:8080"
    restart: always

  www:
    hostname: easytravel-www
    container_name: www
    image: "dynatrace/easytravel-nginx"
    ports:
    - 80
    links:
    - frontend
    - backend
    environment:
      ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
      ET_BACKEND_LOCATION: "easytravel-backend:8080"
    restart: always

  loadgen:
    container_name: loadgen
    image: "dynatrace/easytravel-loadgen"
    links:
    - backend
    - frontend
    - www
    restart: always
    environment:
      ET_APM_SERVER_DEFAULT: "${ET_APM_SERVER_DEFAULT}"
      ET_FRONTEND_URL: "http://easytravel-www:80"
      ET_BACKEND_URL: "http://easytravel-www:8080"
      ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"
